# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
board:
  - nice_nano_v2
  - nice_nano
shield:
  - splitkb_aurora_corne_left
  - splitkb_aurora_corne_right 
  - splitkb_aurora_sweep_left
  - splitkb_aurora_sweep_right 
  - splitkb_aurora_lily58_left
  - splitkb_aurora_lily58_right 
  - kyria_rev3_left
  - kyria_rev3_right 
cmake-args:
  - "-DCONFIG_ZMK_DISPLAY=y -DCONFIG_EC11=y -DCONFIG_EC11_TRIGGER_GLOBAL_THREAD=y -DCONFIG_ZMK_RGB_UNDERGLOW=y -DCONFIG_WS2812_STRIP=y"
